### ISSUE TITLE
Custom HTTP/TLS options and dpdk virtio driver

### ISSUE THREAD

**Issue by rc979** [cisco-system-traffic-generator/trex-core#29]
Hi,

Is there a way to customize the HTTP and HTTPS traffic generation beyond the simple src/dst parameters that one can use with the provided pcap template? Ideally I'd like to specify TLS ciphers, HTTP URIs/paths and host headers.

Also, do you know whether Trex would support the dpdk virtio driver? (http://dpdk.org/doc/guides/nics/virtio.html) 

Thanks.

**Comment by imarom** [comment]
Hi,

If you are asking about stateful traffic generation, TRex supports smart reply of PCAPs.
This means that the flow you have provided is the main template for the traffic generation.
It will be amplified using this template.
We do not support per protocol customization.

For stateless traffic generation, you can generate whichever traffic you like using Scapy.
This won't be stateful, but it is possible to generate two streams and inject them from two interfaces as two directions.

Thanks,
Itay

**Comment by hhaim** [comment]
Hi,
1. Yes, it possible to change header but you will need to write plugin
2. Yes, it is supported -see manual for supported interfaces. However don't expect scale/latency. This interface support only one DP core.

Hanoh
Sent from my iPhone

On 11 Nov 2016, at 10:00, rc979 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Is there a way to customize the HTTP and HTTPS traffic generation beyond the simple src/dst parameters that one can use with the provided pcap template? Ideally I'd like to specify TLS ciphers, HTTP URIs/paths and host headers.

Also, do you know whether Trex would support the dpdk virtio driver? (http://dpdk.org/doc/guides/nics/virtio.html)

Thanks.

-

**Comment by rc979** [comment]
Thank you Hanoh! I missed this detail on the manual, sorry for that, I just
found it. Based on what you are saying I assume you don't support
multiqueues on the virtio dpdk driver, correct? What kind of throughput and
latency can I expect if limited to one DP core?

Thanks again.

**Comment by rc979** [comment]
Thank you Itay.
Not necessarily stateful but just the ability to send a HTTP GET with a
certain URI and host header. The response would be discarded.
I think scapy doesn't support https/tls/ssl natively, it's done via its
layers mechanism, would Trex support this too?
Thanks again.

**Comment by imarom** [comment]
Hi,

I see...basic scapy suite does not contain HTTPS/TLS/SSL...

there are some open source packages that can help with that:
https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/client_hello_rsa.py

We have a patched version of scapy to allow some more capabilities (such as VM with field names),
but you can still use those tools to generate the packet you like and provide it to TRex.

STLPktBuilder(pkt = 'use the scapy extension packet')

Using the example above with stateless:

p = TLSRecord() / TLSHandshake() / TLSClientHello(cipher_suites=[TLSCipherSuite.RSA_WITH_AES_128_CBC_SHA])

stream = STLPktBuilder(pkt = p)

as long as the layers support the basic operations on Scapy layers.

Thanks,
Itay

**Comment by rc979** [comment]
Thank you Itay! Would there be a way to track any part of the HTTP response with the scapy-based approach? Given the fact it's a stateful approach it doesn't seem likely. I'd like to log/store the HTTP response and then discard the flow. If the scapy route isn't feasible can you please let me know how to do this with the pcap templates? I can't seem to find the details on building templates on the docs but maybe I'm not looking on the right places. Thanks again.

**Comment by imarom** [comment]
Hi,

Let me just clarify a bit:
TRex has two modes - stateful and stateless.

In both modes support for RX (getting the packets to software) is limited.
this is because it is usually not needed and has strong impact on performance.
That's why we provide single core to handle RX packets (for latency and other exclusive usages).

In stateful mode, you provide a list of PCAP templates to be amplified using a pool of clients/server.
As Hanoch said, there is also support for plugins (written in C++) that can be applied to each flow.

In stateless, which is client-server approach and provides A Python API you can get more flexibility.

We are currently working on a feature that will allow you to queue RX packets (in a limited size) and fetch them back to Python.
However, this will be used in a low rate (we cannot pass through 1 MPPS of traffic back to Python).

Because you are using TRex and not purely scapy or other Linux tools I assume you need high performance TX...
So I don't see how you can log the HTTP response with this approach.

You might be able with a plugin that handles RX - I need to check if that is possible.

Thanks,
Itay

**Comment by rc979** [comment]
Thanks Itay! If you can let me know a bit more on how to develop the plug
in I'd be great. Couldn't find much on that on the official documentation.
I'd also be interested in the Python RX option even if it's low rate.
Thanks!

**Comment by imarom** [comment]
Stateful plugins currently do not support RX packets.

Stateless RX features are currently under development - I'll update you when the features are tested and released.

Out of curiosity,
what are your planned usages with low rate handling of RX packets ?
why not use plain scapy to handle this ?

Thanks,
Itay
