### ISSUE TITLE
Average throughput calculation in ASTF mode

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#350]
Hi,
Current ASTF statistics counter reports real-time bandwidth, but, it's not easy to calculate exact average throughput.
Currently used method is

begin = gettime()
run_traffic()
wait_on_traffic()
end = gettime()

throughput = received_bytes/(end - begin)

If we add 'duration time' in ASTF statistics counter, then, user can easily calculate throughput.

Definition of 'duration time' per profile
- duration time : time between active(flow > 0) and inactive( flow == 0 )

Will it feasible in trex?

**Comment by egwakim** [comment]
Hi @hhaim ,
If you agree with this suggestion('duration_time' statistics counter in ASTF profile statistics), 
We can contribute it to trex-core, do you agree with this feature?

Thanks
Gwangmoon

**Comment by hhaim** [comment]
@egwakim, I think this duration statistic won't be accurate because the duration timer not wait for flow==0. 
The reason is that at the end of the test it takes time to all flows to close while the bandwidth is reduced slowly. So the average won't be accurate. 

for example. Let's say you want to send 10gbps for 60 sec. if it takes 10 sec to tear-down it will change the average bandwidth to be less that the real 10gbps. 

so the bandwidth over time would be something like this:


```
9, 10, 10, 10, 10, 10, 10, 10, 9, 8, 5, 4, 4, 4, 3, 1, 
```

While what the user wanted is the 10gbps

**Comment by egwakim** [comment]
@hhaim ,
I think the tear-down time should be done within several mili-seconds.
If tear-down is long, then, calculate average_bps when beginning of tear-down can be another option.

Do you have any other idea to resolve it in long tear-down case?

**Comment by hhaim** [comment]
@egwakim tear-down time in TCP depends on the condition of the DUT and we can't assume anything about it as it is under test. In case the DUT have a drop condition re-transmission will affect the tear-down duration. One more thing is that today the TCP counters are global and not per profile so having this duration counter won't make sense. I would leave this to the user that can read the counter periodically (without the wait) and can do calculate the maximum bandwidth. It is a common issue. this is what we did in STF.

**Comment by egwakim** [comment]
Ok,
We decided to use bandwidth of hot-zone(excluding slow-start and tear-down).
