### ISSUE TITLE
STL minimum latency is not accurate 

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#525]
In some case it could be even lower than the minimum. 

```

I am trying to test vxlan latency with traffic rate 2.1 mpps (throughput calculated with pdr 0.001).

I am using below stream and frame_size=1024 and flows=1000 .

        stream = [STLStream(packet = pkt,
                         mode = STLTXCont(pps = 10)),
                  STLStream(packet = pkt,
                            mode = STLTXCont(pps = 9000),
                            flow_stats = STLFlowLatencyStats(pg_id = 12, vxlan=True))
                 ]


1. My question is how average latency is coming less than minimum latency ? 
 2. If I test with traffic 1.9 mpps or less (2.1 is the calculated throughput) , then the average latency is 0 . Is it expected ?

Below is the snapshot of tui . 


Global Statistitcs

connection   : localhost, Port 4501                  total_tx_L2  : 18.11 Gb/sec
version      : STL @ v2.76                           total_tx_L1  : 18.44 Gb/sec
cpu_util.    : 5.33% @ 7 cores (7 per dual port)     total_rx     : 18.06 Gb/sec
rx_cpu_util. : 0.0% / 0 pkt/sec                      total_pps    : 2.1 Mpkt/sec
async_util.  : 0.04% / 1.38 KB/sec                   drop_rate    : 0 b/sec
total_cps.   : 0 cps/sec                             queue_full   : 0 pkts

Latency Statistics

   PG ID     |       12
-------------+---------------
TX pkts      |         825605
RX pkts      |         821360
Max latency  |          13459
Min latency  |             33
Avg latency  |              6
-- Window -- |
Last max     |           2220
Last-1       |           2224
Last-2       |           2191
Last-3       |           2203
Last-4       |           2203
Last-5       |           2209
Last-6       |           2209
Last-7       |           2200
Last-8       |           2186
Last-9       |           2204
Last-10      |           2204
Last-11      |           2221
Last-12      |           2199
Last-13      |           2212
---          |
Jitter       |           1171
----         |
Errors       |       775.46 K

status:  |

browse:     'ESC' - console, 'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
lstats:     'c' - clear, 'h' - histogram toggle,



Global Statistitcs

connection   : localhost, Port 4501                  total_tx_L2  : 18.14 Gb/sec
version      : STL @ v2.76                           total_tx_L1  : 18.48 Gb/sec
cpu_util.    : 5.3% @ 7 cores (7 per dual port)      total_rx     : 18.09 Gb/sec
rx_cpu_util. : 0.0% / 0 pkt/sec                      total_pps    : 2.1 Mpkt/sec
async_util.  : 0.04% / 1.37 KB/sec                   drop_rate    : 0 b/sec
total_cps.   : 0 cps/sec                             queue_full   : 0 pkts

Latency Histogram

   PG ID     |       12
-------------+---------------
10000        |             19
9000         |             10
8000         |              7
7000         |              7
6000         |              9
5000         |             13
4000         |             12
3000         |              9
2000         |          38504
1000         |         436244
900          |            806
800          |           3044
700          |           8850
600          |           7960
500          |           6807
400          |           5654
300          |           5133
- Counters - |
dropped      |        6875944
dup          |              0
out_of_order |         365926
seq_too_high |         714062
seq_too_low  |         365926

status:  \

browse:     'ESC' - console, 'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
lstats:     'c' - clear, 'h' - histogram toggle,


```

**Comment by jsmoon** [comment]
@hhaim I think `uint64_t m_sum` in `CTimeHistogramPerPeriodData` should be `dsec_t` type.

**Comment by bdollma** [comment]
Seems to be I am the last person that touched this code, oops!
Answering both of the questions Hanoch asked:
The average latency is a moving latency, it is of a period of time and not global (unlike min and max).
It is calculated with a low pass filter which weights 50% from the previous period and 50% of the actual period.

https://github.com/cisco-system-traffic-generator/trex-core/blob/6376fbdd3b26074cbb22fd4b3f7d230a5817c7d8/src/time_histogram.cpp#L345

Hence:
1. It can be less than the minimum latency, since the minimum latency is global, and the average latency is calculated as explained.
2. It can be 0.

I am not saying this is the right way to calculate the average latency, I am just explaining the results.

Regarding @jsmoon comment, I agree. `m_sum` is the sum of latencies, hence it makes sense that it needs to be in seconds.

**Comment by hhaim** [comment]
fixed in https://github.com/cisco-system-traffic-generator/trex-core/commit/cea4d9cb19f2d937f32bdc6e470b8b8d36130ce3

**Comment by dheeraj2601** [comment]
Hi Besant Dollma ,

Thanks for explaining as to how average latency can be less than the
minimum latency.
I saw your recent fix on stl latency :
https://github.com/cisco-system-traffic-generator/trex-core/commit/cea4d9cb19f2d937f32bdc6e470b8b8d36130ce3

With the new fix , are the lower latencies taken into consideration for the
calculation of average latency or still ignored ?

Earlier when this issue was raised , Hanon Haim explained as below :
"The  average latency is calculated using the histogram information which
is not accurate as some values, the low ones are not added at all and
considered as zero, this could cause the discrepancy. "

**Comment by bdollma** [comment]
Hi, 
In the end there was a bug in the way we calculated the average.
That was fixed in the the commit you mentioned. 
The average latency calculation is now correct and greater than the minimum latency as it should be.
All the entries (even low ones) are taken in consideration when calculating the average. Also a low pass filter is applied. 
Thanks
