### ISSUE TITLE
Race condition in NAT learning mode

### ISSUE THREAD

**Issue by gshimansky** [cisco-system-traffic-generator/trex-core#53]
I am trying to use t-rex v2.28 to test my NAT implementation (it is an example in [YANFF project](https://github.com/intel-go/yanff)). When I run t-rex like this I almost always get a failed assertion in release, and quite often in debug:

`./t-rex-64-debug -f cap2/myimix1.yaml -c 8 -m 50 -d 30 --learn-mode 1`

Assertion stack trace looks like this

```
assert: ../../src/bp_sim.h:4159 void CFlowGenListPerThread::associate(uint32_t, CGenNode*) Assertion 'm_flow_id_to_node_lookup.lookup(fid)==0' failed.

*** traceback follows ***

1             0x609083 __assert_fail + 768
2             0x5c06c3 CFlowGenListPerThread::associate(unsigned int, CGenNode*) + 73
3             0x5ab54c CCapFileFlowInfo::generate_flow(CTupleTemplateGeneratorSmart*, CNodeGenerator*, double, unsigned long, CFlowYamlInfo*, CGenNode*) + 702
4             0x5c0b5b CFlowGeneratorRecPerThread::generate_flow(CNodeGenerator*, double, unsigned long, CGenNode*) + 75
5             0x5b334d CFlowGenListPerThread::generate_flows_roundrobin(bool*) + 319
6             0x5c5f91 int CNodeGenerator::flush_file_realtime<24, false>(double, double, CFlowGenListPerThread*, double&) + 843
7             0x5b23bf CNodeGenerator::flush_file(double, double, bool, CFlowGenListPerThread*, double&) + 215
8             0x5b42fb CFlowGenListPerThread::start_generate_stateful(std::string, CPreviewMode&) + 1179
9             0x5ee597 CGlobalTRex::run_in_core(unsigned char) + 613
10            0x5f048c ./_t-rex-64-debug() [0x5f048c]
11            0x93e0ff eal_thread_loop + 738
12      0x7f6f7505736d /lib64/libpthread.so.0(+0x736d) [0x7f6f7505736d]
13      0x7f6f740bfb8f clone + 63
```

I attached YAML config file and pcap templates that I use.
[imix.zip](https://github.com/cisco-system-traffic-generator/trex-core/files/1246823/imix.zip)

**Comment by hhaim** [comment]
First, thanks for reporting this. 
In your case there is no meaning for nat "learning"  as you have UDP with one direction. You can use stateless mode without any problem (with NAT)  which is much faster than stateful for those use-cases or Stateful without the learn mode. 

There is a need for learn-mode=1 in this case:
 1. Two direction UDP flows (e.g. dns.yaml) 
2. Firewall configured with NAT  that drop IPv4 option (e.g. Firepower/ASA)

We have a limitation with the number of bits we have to create the association between the remote flows and local flow and this issue can't be solve.
The Advance Stateful is going to solve this issue from the root. 

and one last thing, we will convert this assert to a better message  
thanks,
Hanoh

**Comment by gshimansky** [comment]
Hello Hanoh

Actually I did some modifications with IMIX templates that I found in t-rex distribution. In order to test my NAT in two directional traffic I duplicated UDP packets and edited second packet with wireshark to make it go back from server to client (edited MAC and IP addresses changing source to destination). That is why I think I need learn-mode 1 flag. I attached my YAML and PCAP files.

I think there is a bug because out of 10 launches of t-rex release I get 2 successful and 8 failed on assert. The bigger number I specify in -m switch, the less change for a successful launch. On debug version I also get successful and failed runs. Because of this inconsistency I assumed that there should be some kind of race condition when many threads compete for the same resource with no consistent result.

**Comment by hhaim** [comment]
Understood. Didn't look into the pcap.
 As I said it is not a race, it is just not enough bits to sync UDP  flows in this mode and this is expected in high rate (We would fix the error message)

What you can do is the following: 
1. Move to learn mode 2
2. Move to short TCP flows with learn mode 1 (there are much more bits to sync the flows)
BTW I like the golang framework wonder if we can use it as a L2 emulation event drive for our project.
Today we are using python but looking for faster one.
 
Advance Stateful will solve this issue 

Hanoh

**Comment by gshimansky** [comment]
Yes I tried learn-mode 2, and it does work without crashes, but I found it to be too slow for my needs. I need to test my NAT with two 40Gbps channels (in and out), and with learn-mode 2 I couldn't make t-rex to generate enough traffic.
Thank you for suggestion. I will try to find a TCP flow with IMIX packets pattern.

**Comment by hhaim** [comment]
It make sense that mode=2 is slower from DPDK perspective as there are two mbufs in this case.
But thinking about imix and NAT again,I think it is not a good test as TCP/UDP scenario when there is always new flows/translations. In your case there is a very small burst of new flows and then

**Comment by hhaim** [comment]
looking again into your profile again
     - name: cap2/myudp_594B.pcap
       cps   : 64725
       ipg   : 10000
       rtt   : 10000
       w     : 1
       limit : 4444

You are using "limit" which means that there is going to be a burst of translation at the test start and then only NAT lookups.
There are two things that you need to measure for NAT
1) The rate of lookups (PPS) -IMIX 
2) The rate of new connections  (CPS)
To test #2 better to have a PCAP file with SYN/SYN-ACK flow (take from simple_http. pcap the first two packets) and *remove* the "limit". This way you will find the rate of new CPS that you can handle (or TRex can handle-- it is a bit slow in case of TRex because we have one core for that with messaging)
For doing #1 it is a bit trickier because you want to make TRex translation phase slow and after that run the traffic faster. The way to do it is like that 
Make this type of PCAP (the first packets with long IPG) and then 100 packet with very short IPG. 

time  | packet   | direction 
0       |   UDP        ->
5      |    UDP   |   <-
10    |    UDP   |  ->
11    |   UDP    | <-   
12    |    UDP   |  ->
13    |   UDP    | <-   
14    |    UDP   |  ->
15    |   UDP    | <-   
..
100 packets

**Comment by gshimansky** [comment]
Yes you are right that my scenario doesn't test new connections creation well. It does create about 53K of connections at the beginning and then just sends packets over them back and forth. It is primary oriented to test the translation and sustainable speed transfer which we can do utilizing different numbers of CPU cores.

I did try simple_http.pcap template, but I stumbled into a problem with ports reuse. With big number in -m parameter for high bandwidth it tries to create more than 64K connections and I run out of ports on the interface. I am currently working on port allocator to handle TCP FIN/RST condition to allow ports reuse after connection is terminated, but I am still not sure whether in real scenarios ports may be reused immediately instead of remaining for some significant time in TIME_WAIT state. If the latter, I will still not get the maximum bandwidth utilization with simple_http template. Another problem with this template is that it is not symmetrical, because data mostly flows from server to client. It is not good for pure speed benchmaking. But your idea to measure new CPS separately is a good one. We didn't think of this metrics before.

**Comment by hhaim** [comment]
With CNAT you can define multi Outside IP address, This will solve the 64K ports issue (for one outside) You need to wait for port reuse.

Simple HTTP or SFR is a another good benchmark because it is more realistic and measure both CPS/PPS

Hanoh
Sent from my iPhone

On 25 Aug 2017, at 18:13, Gregory Shimansky <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes you are right that my scenario doesn't test new connections creation well. It does create about 53K of connections at the beginning and then just sends packets over them back and forth. It is primary oriented to test the translation and sustainable speed transfer which we can do utilizing different numbers of CPU cores.

I did try simple_http.pcap template, but I stumbled into a problem with ports reuse. With big number in -m parameter for high bandwidth it tries to create more than 64K connections and I run out of ports on the interface. I am currently working on port allocator to handle TCP FIN/RST condition to allow ports reuse after connection is terminated, but I am still not sure whether in real scenarios ports may be reused immediately instead of remaining for some significant time in TIME_WAIT state. If the latter, I will still not get the maximum bandwidth utilization with simple_http template. Another problem with this template is that it is not symmetrical, because data mostly flows from server to client. It is not good for pure speed benchmaking. But your idea to measure new CPS separately is a good one. We didn't think of this metrics before.

-

**Comment by hhaim** [comment]
Will close this if it OK

**Comment by gshimansky** [comment]
No problem in closing it from my side.
