### ISSUE TITLE
Not Able To Achieve 100Gbps Tx Speed with Trex 2.9 on E810 100G NIC

### ISSUE THREAD

**Issue by utkarsh0902311047** [cisco-system-traffic-generator/trex-core#747]
Hi,
I have two Ubuntu systems. Each have one E810 NIC card. I am trying to generate 100Gbps data from one port of NIC to send to the other NIC card. I am using Trex 2.9 for the same but the max Tx speed it is showing is only 52Gbps. What should I do ?
Please help.

**Comment by bdollma** [comment]
Hi, 
Can you please provide some more information?

1. How did you run TRex? Please provide the exact command.
2. What profile are you using? Are we talking about L2 Bps or L1 Bps?
3. Please provide a screenshot of the dashboard that the `tui` command provides in the console

Thanks

**Comment by utkarsh0902311047** [comment]
Thank you for replying
COMMANDS:
1. ./t-rex-64 -i -c 7 --mbuf-factor 0.2
2. ./trex-console
3. trex> tui
4. start -f stl/bench.py -m 100% --port 0 -t size=64,vm=cached
![Screenshot from 2021-07-23 22-51-55](https://user-images.githubusercontent.com/78134056/126800744-4976b4f0-9cf0-4c6c-a75e-94646cfdd6ff.png)
![Screenshot from 2021-07-23 22-57-28](https://user-images.githubusercontent.com/78134056/126800857-a0f9efc5-ef78-48b0-b449-634540deadc3.png)

Sorry I am not clear with your second question?

**Comment by utkarsh0902311047** [comment]
I tried to change the packet size to 1024 and it reached 100% line rate. I hope that was the problem. Still your input will be valuable.
Also, please can you give me some idea what is Tx bps L2 and Tx bps L1?

**Comment by bdollma** [comment]
Hi again,

1. Regarding my second question: You are sending 68 Gbps actually (L1) but this is only 52Gbps L2 since the packets you are sending are small, 64 bytes. When they sell you the NIC and tell you its 100Gbps they talk about L1. However there is some extra bytes added to each L2 frame such as IFG, FCS etc. This has a major impact on small packets and a minor one in big packets, look [here](https://support-kb.spirent.com/resources/sites/SPIRENT/content/live/FAQS/10000/FAQ10739/en_US/Layer%201%20and%20Layer%202%20bits%20per%20second%20calculation.pdf)
2. You limitation is coming from CPU util. Your CPU utilization seems to have reached the maximum hence it can't generate more. Adding more cores is a possibility, however there seems to be a problem with `queue_full`. Queue full will make the CPU spin and reach high utilization. 
Thanks,

**Comment by utkarsh0902311047** [comment]
![Screenshot from 2021-07-23 23-14-46](https://user-images.githubusercontent.com/78134056/126803216-31635a5c-dc99-446d-af6b-6aea88c2b369.png)

Now I am getting this result after increasing the packet size to 1024. I hope its ok now.
Thank you for all your help :)

**Comment by utkarsh0902311047** [comment]
> Hi again,
> 
>     1. Regarding my second question: You are sending 68 Gbps actually (L1) but this is only 52Gbps L2 since the packets you are sending are small, 64 bytes. When they sell you the NIC and tell you its 100Gbps they talk about L1. However there is some extra bytes added to each L2 frame such as IFG, FCS etc. This has a major impact on small packets and a minor one in big packets, look [here](https://support-kb.spirent.com/resources/sites/SPIRENT/content/live/FAQS/10000/FAQ10739/en_US/Layer%201%20and%20Layer%202%20bits%20per%20second%20calculation.pdf)
> 
>     2. You limitation is coming from CPU util. Your CPU utilization seems to have reached the maximum hence it can't generate more. Adding more cores is a possibility, however there seems to be a problem with `queue_full`. Queue full will make the CPU spin and reach high utilization.
>        Thanks,

Btw, how to put more cores?

**Comment by bdollma** [comment]
Yep, that NIC is getting stressed.
You are welcome.

Regarding the number of cores you define it using the `-c` flag.

**Comment by hhaim** [comment]
@utkarsh0902311047 the support of E810 is very basic because the DPDK driver is new and does not support all the features yet. Intel is working to solve this and only after that we would be able to measure the real chip performance.  it is written in the release notes
