### ISSUE TITLE
The counters returned by RPC command "get_port_stats" are always zero

### ISSUE THREAD

**Issue by linsergit** [cisco-system-traffic-generator/trex-core#89]
Hi,

I'm trying to fetch the statistics for each port in my application by calling the RPC command "get_port_stats" to TRex server, then I can parse the Json response to get the counters.

the command can send out and received the response from TRex sever sucessfully, but all counter's values are 0, the valid counts values can be shown in console log.

**Comment by imarom** [comment]
Hi,

This is being handled as part of a larger refactoring project we currently handling.

Will update about this issue when it is solved.

Thanks,
Itay

**Comment by linsergit** [comment]
Thanks @imarom 

Do you have any schedule plan for this refactoring,  you mentioned it's a "lager" one, so I want to know if I need wait for a longer time.

**Comment by imarom** [comment]
Should be in the near future (few weeks).

Itay

**Comment by egwakim** [comment]
Hi Itay,
Can you assume when it's available?
Can I add this feature on your working branch?

**Comment by imarom** [comment]
few days...

My branch is still unstable but I can push it to my GithHub account and you can develop on top of it

**Comment by egwakim** [comment]
Hi Itay,
I checked the current TRex features. 
Measurement period can be ambiguous in this case.
But, I think we can refer statistics in async port because all statistics should be same in same TRex instance.
How about providing same statistics value with async port when user calls 'get_port_stats' ?
Statistics items will be differ, but value of same item will be same.

And, can you share your working branch? I want to check the current refactoring code.

Thanks

Best Regards
Gwangmoon

**Comment by egwakim** [comment]
Hi Itay,
Any comment on my questions?

**Comment by hhaim** [comment]
fixed in v2.43
